# Generated by Django 5.0.3 on 2024-04-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
